### ISSUE TITLE
Feature request: compatibility with Mageplaza OneStepCheckout

### ISSUE THREAD

**Issue by SilvanLaroo** [tig-nl/postcode-magento2#1]
Hi,

This extension works great on the default checkout page of Magento 2. In most of our projects we're using the [OneStepCheckout from Mageplaza](https://www.mageplaza.com/magento-2-one-step-checkout-extension/). Are there any plans to support this extension?

Regards,
Silvan

**Comment by tig-rikjonkmans** [comment]
Hi @SilvanLaroo, 

Yes there is, but this is not in process yet. I will keep you up to date when there is any progress.

Kind Regards,
Rik

**Comment by tig-rikjonkmans** [comment]
Hi @SilvanLaroo,
We just released V1.1.2 which is compatible with the oneStepCheckout from Mageplaza.
When you update the extension there will be a new config field available for performance behaviour.
![image](https://user-images.githubusercontent.com/23359911/40005648-c62c9ef8-5798-11e8-8392-b012e762a877.png)

Kind Regards and enjoy,
Rik

**Comment by tig-rikjonkmans** [comment]
@SilvanLaroo,
Because i forget to upgrade the package.json, packagist.org did not synced with our repository. Yesterday i have released 1.1.3 so it is possible to upgrade with composer again.
