### ISSUE TITLE
Magento 2.3.1/2.2.8 support

### ISSUE THREAD

**Issue by tig-dennisvanderhammen** [tig-nl/postcode-magento2#12]
## Please follow the guide below

- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like.
- We may ask some questions or ask you to provide addition information after you placed your request.

---

### Make sure you are using the *latest* version: https://tig.nl/totale-aanbod-extensies/extensie-postcode-service/
Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running the latest version of the TIG Postcode Magento extension.

---

### What is the purpose of your *issue*?
- [x] Feature request (request for a new functionality)
- [ ] Bug report (encountered problems with the TIG Postcode Magento extension)
- [ ] Extension support request (request for adding support for a new extension)
- [ ] Other

---

### If the purpose of your issue is a *feature request*
- As a merchant or developer I’d like to be able to update to Magento 2.3.1 with the Postcode extension installed in order to stay up-to-date with the latest Security patches.

### TIG support

- Please ask your question in English to ensure that your issue can help other people internationally. Nevertheless we will respond in English.

**Comment by albsa** [comment]
Please check this ASAP so we can upgrade to the latest version, thanks!!

**Comment by tig-dennisvanderhammen** [comment]
@albsa, we're currently working on it. Once we've tested the extension in combination with this update we'll release a new version that includes the composer.json files that are supported!

**Comment by tig-dennisvanderhammen** [comment]
HI @albsa,

We just released version 1.2.2 for the Postcode M2 extension. This one is compatible with Magento version 2.2.8 and 2.3.1.
