### ISSUE TITLE
[BUG] House number disappears from shipping info after page refresh

### ISSUE THREAD

**Issue by glevhen** [tig-nl/postcode-magento2#13]
Magento 2.3.2
Theme: Magento/luma
tig/postcode-magento2: 1.2.4
Checkout usage: Two Step Checkout Luma
House number field: Street address line 1

On the shipping step fill address details via success postcode autocomplete and go to the payments step
the house number available in the shipping info 
![image](https://user-images.githubusercontent.com/16398798/72450502-2826c000-37c3-11ea-8879-0ac1b9714707.png)
refresh the page and house number disappears from shipping address info
![image](https://user-images.githubusercontent.com/16398798/72450763-8d7ab100-37c3-11ea-918e-8b9584fad952.png)

**Comment by tig-jaspersmits** [comment]
Hi @glevhen ,

Thanks for submitting this. Unfortunate to hear that this happens. I've just tested this and been able to reproduce it. This has been placed on our backlog to be solved. Keep an eye on the release notes to see when the new version is released. 

Kind regards,

Jasper
TIG
