### ISSUE TITLE
[BUG] Layout xml defines layout

### ISSUE THREAD

**Issue by rikwillems** [tig-nl/postcode-magento2#16]
We experience our header appearing at the bottom of the checkout. I found that removing `layout="checkout"` from `view/frontend/layout/checkout_index_index.xml` fixes the issue. A module should not set the layout for an existing handle, in my opinion.

**To Reproduce**
This is probably template or custom work related. 

**Expected result**
Header showing as normal

**Workaround**
Remove `layout="checkout"` from `view/frontend/layout/checkout_index_index.xml`

** Please complete the following information**
- Magento version: 2.3.5-p1

**Comment by tig-jaspersmits** [comment]
Hi @rikwillems ,

Thanks for informing us about this. I will let a developer know and me or my colleague will get back to you with a reply.

Kind regards,
Jasper
TIG

**Comment by tig-jaspersmits** [comment]
@tig-dennisvanderhammen could you share your opinion on this?

**Comment by tig-dennisvanderhammen** [comment]
Interesting. We'll have to see how this affects the current layout. If nothing breaks in the current flow, we'll remove this from the layout.

**Comment by tig-jaspersmits** [comment]
Hi @rikwillems ,

I've added this to the backlog. We will implement this in an upcoming release.
You can keep an eye on the release notes here: https://docs.tig.nl/x/B4FaAg

Kind regards,
Jasper
TIG

**Comment by tig-dennisvanderhammen** [comment]
Hi @rikwillems,

Thank you again for submitting this issue. We just updated the extension and your change is included. For a full overview of changes, please check https://docs.tig.nl/x/B4FaAg

**Comment by rikwillems** [comment]
Thank you!
