### ISSUE TITLE
[FEATURE] Postcode validation in customer account

### ISSUE THREAD

**Issue by rikwillems** [tig-nl/postcode-magento2#18]
As a user I want postcode validation when I insert/update my address in my account address book.

Although available in the checkout the customer account address book allows me to fill in any value.

**Comment by tig-jeffreybranderhorst** [comment]
Hi @rikwillems ,

This feature is standing on our backlog, it is an good feature to add! Thank you for submitting this and for thinking along with us to make the extension even better! 

Have a great day,
Jeffrey

**Comment by rikwillems** [comment]
This appears to be added to v1.3.3
