### ISSUE TITLE
[FEATURE] Magento 2.3.6 compatibility

### ISSUE THREAD

**Issue by rikwillems** [tig-nl/postcode-magento2#20]
The latest version of this module doesn't install on a fresh 2.3.6 installation. 
```
composer require tig/postcode-magento2
Using version ^1.3 for tig/postcode-magento2
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for tig/postcode-magento2 ^1.3 -> satisfiable by tig/postcode-magento2[1.3.0].
    - Can only install one of: magento/module-checkout[100.4.0, 100.3.6].
    - Can only install one of: magento/module-checkout[100.4.0, 100.3.6].
    - Can only install one of: magento/module-checkout[100.4.0, 100.3.6].
    - Conclusion: install magento/module-checkout 100.4.0
    - Installation request for magento/module-checkout (locked at 100.3.6) -> satisfiable by magento/module-checkout[100.3.6].
```

**Comment by tig-jaspersmits** [comment]
Hi @rikwillems ,

Thanks for submitting this. I've just tested this and I'm unable to reproduce this problem on a 2.3.6 environment.

`[TIG v1.13.0 10:36:15] - <Linux x86_64> - (app @ server.tig.nl)  # php73 /bin/composer require tig/postnl-magento2
Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2.0 is about to be released and the older 1.x releases will self-update directly to it once it is released. To avoid surprises update now to the latest 1.x version which will prompt you before self-updating to 2.x.
Using version ^1.9 for tig/postnl-magento2
./composer.json has been updated
Loading composer repositories with package information
Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2.0 is about to be released and the older 1.x releases will self-update directly to it once it is released. To avoid surprises update now to the latest 1.x version which will prompt you before self-updating to 2.x.
Updating dependencies (including require-dev)
Package operations: 4 installs, 0 updates, 0 removals
As there is no 'unzip' command installed zip files are being unpacked using the PHP zip extension.
This may cause invalid reports of corrupted archives. Besides, any UNIX permissions (e.g. executable) defined in the archives will be lost.
Installing 'unzip' may remediate them.
  - Installing laminas/laminas-barcode (2.8.2): Loading from cache
  - Installing setasign/fpdi (v2.3.4): Loading from cache
  - Installing setasign/fpdf (1.8.2): Loading from cache
  - Installing tig/postnl-magento2 (1.9.5): Loading from cache
laminas/laminas-barcode suggests installing zendframework/zendpdf (ZendPdf component)
Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.
Package flow/jsonpath is abandoned, you should avoid using it. Use softcreatr/jsonpath instead.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Package sebastian/finder-facade is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files
60 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
PHP CodeSniffer Config installed_paths set to ../../phpcompatibility/php-compatibility,../../codeception,../../magento/magento-coding-standard
[TIG v1.13.0 10:37:13] - <Linux x86_64> - (app @ server.tig.nl)  # php73 bin/magento module:enable TIG_PostNL
The following modules have been enabled:
- TIG_PostNL

To make sure that the enabled modules are properly registered, run 'setup:upgrade'.
Cache cleared successfully.
Generated classes cleared successfully. Please run the 'setup:di:compile' command to generate classes.
Info: Some modules might require static view files to be cleared. To do this, run 'module:enable' with the --clear-static-content option to clear them.`

Kind regards,
Jasper
TIG

**Comment by tig-jaspersmits** [comment]
@rikwillems ,

Ignore my previous comment... it's about the postcode service of course.
I can confirm this doesn't work yet, my colleague is looking into it.

Kind regards,
Jasper
TIG

**Comment by rikwillems** [comment]
Hi @tig-jaspersmits any news or progress on this?

**Comment by tig-jaspersmits** [comment]
Hi @rikwillems ,

This should work for Magento 2.3.6 now.

Kind regards,
Jasper
TIG
