### ISSUE TITLE
[QUESTION] Amasty OneStepCheckout fields order

### ISSUE THREAD

**Issue by Paulsky** [tig-nl/postcode-magento2#22]
**Question**
Hello, with the Amasty OneStepCheckout we can rearrange the shipping and billing fields. But I have no succes rearranging the address fields.

I would like to display the postcode/housenumber (shipping-address-fieldset) first, after that the address (street) field. How can I accomplish that? Thank you in advance!

**Comment by tig-jeffreybranderhorst** [comment]
Hi @Paulsky ,

At this moment to change the sort order you will need to change it in the code. The next version of the extension we are going to release will have this as an option in the backend. What mean with the upcoming version you can change it at in the backend. If you already want to change it, can you then mail us at support@tig.nl so we can assist your further.

Have a great day,
Jeffrey

**Comment by Paulsky** [comment]
Hello @tig-jeffreybranderhorst,

Thank you very much for your reply. I understand. Do you have a rough ETA of the next version?

This way, I can let my client choose whether we should proceed the customization of the current version, or just wait for the next version.

Have a nice day and thank you!

**Comment by tig-jeffreybranderhorst** [comment]
Hi @Paulsky ,

Our plan is to release it before the end of February.  

Have a great day,
Jeffrey

**Comment by Paulsky** [comment]
Alright! Thank you🙏
