### ISSUE TITLE
[FEATURE] Magento 2.4.2

### ISSUE THREAD

**Issue by jorgb90** [tig-nl/postcode-magento2#26]
Is it compatible?

**Comment by tig-jeffreybranderhorst** [comment]
Hi @jorgb90 ,

We have placed testing of the extension on 2.4.2 on our next sprint planning. We will update the extension compatibility if we find no problems with the new release!

Have a great day,
Jeffrey

**Comment by stefanluk** [comment]
@tig-jeffreybranderhorst Does this also include compatibility with 2.3.6-p1 ?

**Comment by tig-jeffreybranderhorst** [comment]
Hey @stefanluk ,

Yes this also includes the 2.3.6-p1 version, we will also test that version.

Have a nice day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment]
Hi @stefanluk and @jorgb90 ,

We tested our modules with the new magento versions. We also updated the extension so the support is added to our live extension. You can update to the newest version to get the support!

Have a nice day,
Jeffrey
