### ISSUE TITLE
[BUG] Module causes slow checkig payment step

### ISSUE THREAD

**Issue by Tjitse-E** [tig-nl/postcode-magento2#27]
**To Reproduce**
1. Setup Magento 2.4.0/2.4.1/2.4.2 and install postcode-magento2
postcode-magento2
2. Enable as much payment methods as possible
3. Try to order a product
4. Try to select a payment method

**Expected result**
Switching will go instant, like a stock Magento 2 shop.

**Actual result**
Switching is delayed. Every switch will cause you a few seconds with only 4 (internal) payment methods enabled. When you enable 10 payment methods (for example, you are using a PSP and are offering Paypal, Mastercard, etc), the wait time will grow exponentially. With 10 payment methods it will take you around 20 seconds to switch.

**Workaround**
None

**Screenshots**
Video:
https://user-images.githubusercontent.com/14849044/108263908-20c0ab80-7167-11eb-8251-19555dda5349.mov

** Please complete the following information**
- Mageto 2.4.2/2.4.1/2.4.0
- PHP version: using PHP 7.3

**Comment by tig-jeffreybranderhorst** [comment]
Hi @Tjitse-E ,

I just tested and indeed notice that is become slower. I will create an issue on our backlog for this.  Thank you for submitting this issue.

Have a great day,
Jeffrey

**Comment by Esteraa** [comment]
@tig-jeffreybranderhorst Any idea what the timeline will be on this issue? The update to M2.4.x is depending on the issue above.

**Comment by tig-jeffreybranderhorst** [comment]
Hi @Esteraa ,

We got it on our sprint as task, as soon we know a eta we will update it here!

Have a great day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment]
Hi @Tjitse-E and @Esteraa ,

The newest version we released includes the fix for this issue. If you update it should be working again!

Have a nice day,
Jeffrey
