### ISSUE TITLE
[BUG] Customer account implementation does not check enabled status

### ISSUE THREAD

**Issue by rikwillems** [tig-nl/postcode-magento2#28]
The new customer account implementation does not check if the module is enabled for the store view. This means the javascript code that hustles the fields is always loaded.

## Expected behaviour
Frontend implementation respects enabled/disabled status at store level.

**Comment by tig-jeffreybranderhorst** [comment]
Hi @rikwillems ,

Thank you for submitting this, I will test this and place it on the backlog so we can make a fix for it!
Thank you !

Have a great day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment]
Hi @rikwillems ,

This is fixed in the newest version of the extension!

Have a great day,
Jeffrey
