### ISSUE TITLE
Customer account implementation does not use `StreetFields` service

### ISSUE THREAD

**Issue by rikwillems** [tig-nl/postcode-magento2#29]
The `StreetFields` service create the street field based on set configuration. The customer account implementation does not use this service and always returns a three item array in `CustomerForm`. We use the setting to store the address in one line so the form on `customer/address/edit/id/1` returns an error `"Adres" mag niet meer dan 1 regels bevatten.`.

**Comment by tig-jeffreybranderhorst** [comment]
Hi @rikwillems ,

Thank you for submitting this! We are going to investigate it.

Have a great day,
Jeffrey
