### ISSUE TITLE
POSTNL-0124 : Unable to extract the house number, could not find a number inside the street value

### ISSUE THREAD

**Issue by kaushalsutharhs** [tig-nl/postcode-magento2#3]
Magento ver. 2.2.3
postcode-magento2 version:1.1.3
OneStepCheckout : onestepcheckout/iosc (onestepcheckout.com)

At checkout, I'm getting above error mentioned in the title.

You can also check the image below.
![screenshot from 2018-06-12 20-44-43](https://user-images.githubusercontent.com/16755576/41299636-87bc85d4-6e81-11e8-98bc-00d19a27e55c.png)

**Comment by tig-rikjonkmans** [comment]
Hi @kaushalsutharhs,

We are not full compatible with the IOSC yet, this is on our backlog. Also the extension is only compatible with PostNL v1.3.2 or higher and the PostNL extension is also not full compatible with the IOSC.

Separate, the extensions might seems to work, but they still have issues, so be aware of that.  
I will keep you posted.

**Comment by kaushalsutharhs** [comment]
@tig-rikjonkmans Okay thanks.

**Comment by Pagayo** [comment]
Has this issue ever been solved?

**Comment by tig-dennisvanderhammen** [comment]
Hi @Pagayo, we do have something in beta right now, but this seems to be causing issues trying to run setup:di:compile. So currently this is still pending.
