### ISSUE TITLE
[BUG] Checkout street does not merge housenumber in BE

### ISSUE THREAD

**Issue by rikwillems** [tig-nl/postcode-magento2#30]
Because of `Plugin/Address/LayoutProcessor.php:157` in BE the core group component is used while the TIG component is used for NL: `view/frontend/web/js/view/form/fields.js`. Now the housenumber and additions are not merged on the street field in BE.

**Comment by tig-jeffreybranderhorst** [comment]
Hi @rikwillems ,

Thank you for submitting this! We will investigate this further and fix it!

Have a great day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment]
Hey @rikwillems ,

In our newest extension this is fixed. You need further support after installing the newest version of the extension you can always contact us at support@tig.nl

Have a great day,
Jeffrey
