### ISSUE TITLE
[BUG] Please summarize your bug issue here

### ISSUE THREAD

**Issue by downforce80** [tig-nl/postcode-magento2#31]
**To Reproduce**
1. Add products to basket
2. Continue 
2. Login as customer
3. Proceed to shipping
4. Proceed to payment
5. Add discount code

**Expected result**
Discount code gets applied

**Actual result**
Order is stuck with loading spinner wheel

**Workaround**
don't apply discount
 
**Screenshots**

** Please complete the following information**
- Magento 2.2.4
- Postcode_magento2 1.3.3

**Comment by tig-jeffreybranderhorst** [comment]
Hi @downforce80 ,

Thank you for submitting this, we are going to investigate this further and fix the issue. 

Have a great day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment]
Hi @downforce80,

This should be fixed in our newest version of the extension! 

Have a great day,
Jeffrey
