### ISSUE TITLE
[BUG] Edit link not visible in checkout

### ISSUE THREAD

**Issue by Aquive** [tig-nl/postcode-magento2#35]
**Question**

When this extension is enabled, the `edit` link in the checkout for a newly added address disappears, comparing it to a stock Magento installation.

I see it is coming from this line: https://github.com/tig-nl/postcode-magento2/blob/master/view/frontend/web/template/shipping-address/address-renderer/default.html#L27

My question is, why is the `edit` link hidden/not visible?

**Comment by tig-jeffreybranderhorst** [comment]
Hi @Aquive,

The edit button should be displayed, I just tested this on our test site to be sure.  If you are having issues with this, could you contact us at support@postcodeservice.com, so we can help you investigate this on your website?

Have a great day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment]
Hi @Aquive ,

My last message is incorrect, I see my test site was on the develop version of the postcode service.  In the live version, this is indeed an error that will be fixed in our next release!

Have a great day,
Jeffrey

**Comment by Aquive** [comment]
@tig-jeffreybranderhorst great to hear. Any idea when the release will be?

**Comment by tig-jeffreybranderhorst** [comment]
Hi @Aquive ,

The planning is to release this week!

Have a great day,
Jeffrey
