### ISSUE TITLE
Coupon code field in checkout not working

### ISSUE THREAD

**Issue by Aquive** [tig-nl/postcode-magento2#36]
**To Reproduce**
1. Add a discount coupon code from the admin
2. Try to use the coupon code in the checkout in frontend (not from the cart)
3. The spinner keeps spinning without a result

**Expected result**
I expect the coupon code to be applied.

**Actual result**
Loader spinner just keeps spinning.

**Workaround**
None (that I know of). Only way to make the coupon field working is to disable tig postcode extension

**Screenshots**
![Afrekenen (3)](https://user-images.githubusercontent.com/197229/148746174-29f06543-8456-49ab-a205-b116b607d817.png)

- Magento version: Magento 2.4.3-p1
- PHP version: 7.4.8
- tig/postcode-magento2: 1.4.0

**Comment by tig-jeffreybranderhorst** [comment]
Hi @Aquive,

Thank you for submitting this issue, we followed your steps but could not reproduce it.  I used the same Magento and Postcode version on a clean Magento install. Could you contact us at support@postcodeservice.com, so we can help you further and test this on your environment?   
![image](https://user-images.githubusercontent.com/23314965/148755718-6396ad6a-1cac-4757-95ee-abac5a269edf.png)

Have a great day,
Jeffrey

**Comment by Aquive** [comment]
@tig-jeffreybranderhorst I emailed a while ago but got no response. I just resend it to be sure. Can you check/confirm if you got the email?

**Comment by tig-jeffreybranderhorst** [comment]
Hey @Aquive,

Thank you, I could not find your email in our support system. So I just made an issue myself, you should have received a mail of this support issue. If you can respond on the issue, we can help you further.

Have a great day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment]
Hi @Aquive,

Thank you for the update, good luck with the testing. We also have contact via the e-mail, but let us know if you find anything! 

Have a great day,
Jeffrey
