### ISSUE TITLE
[BUG] Street field missing after address edit

### ISSUE THREAD

**Issue by Aquive** [tig-nl/postcode-magento2#37]
**To Reproduce**
1. Make sure to have an account with an address.
2. Try to change and save the street and house number. 

**Expected result**
A complete address (including street field)

**Actual result**
An address where the street field is not present.

**Workaround**
None (That I know of)

**Screenshots**
See attached screenshot. 

** Please complete the following information**
- Magento version: 2.4.3-p1
- PHP version: 7.4.8
- TIG Postcode extension version: 1.4.1

<img width="1226" alt="Schermafbeelding 2022-01-27 om 16 03 58" src="https://user-images.githubusercontent.com/197229/151815431-8445b79e-bfc2-4522-a97c-22cb34c35b93.png">

**Comment by tig-jeffreybranderhorst** [comment]
Hi @Aquive,

Thank you for submitting this issue. We will investigate it further!  Could you tell us how your address rows are configured and how the "advanced configuration" is configured in the postcode extension? 

And are the settings the same for #38 and #39 ?

Have a great day,
Jeffrey

**Comment by Aquive** [comment]
Hi @tig-jeffreybranderhorst 

Thanks for your reply. The advanced config is as the screenshot attached below. Which other config do you want to see as an additon? If you could specifiy that, I could look it up.

And yes, the setting are exactly the same for the other issues too.

Thanks!


![Configuration-Settings-Stores-Magento-Admin (3)](https://user-images.githubusercontent.com/197229/151826049-c1425c59-945f-4555-875b-3cb506ce83cf.png)

**Comment by tig-jeffreybranderhorst** [comment]
Hi @Aquive,

Thank you for the update. We would like to see your settings for the amount of lines in the street address. I think it is 3 with the settings you showed us, but to be sure.  The settings can be found in Stores > configuration > Customers > Customer configuration > name and address options it should be the first option. 
![image](https://user-images.githubusercontent.com/23314965/151928175-ca90ddfc-8025-428a-b6de-9e995d93b385.png)

Have a great day,
Jeffrey

**Comment by Aquive** [comment]
Hi Jeffrey,

It is set to the default value, 3. See screenshot below.

![Uploading Configuratie-Settings-Stores-Magento-Admin.png…]()

**Comment by tig-jeffreybranderhorst** [comment]
Hey @Aquive,

I have just sent you a mail to give you direct support and investigate this further because on my test account the address is saved correctly after changing. 

Have a great day,
Jeffrey

**Comment by rikwillems** [comment]
I ran into this issue as well. You can use this patch to fix it:

```
--- a/Plugin/Address/Management/CustomerForm.php
+++ b/Plugin/Address/Management/CustomerForm.php
@@ -74,7 +74,7 @@ class CustomerForm

         $attributes = [
             'tig_housenumber' => $request->getPostValue('tig-housenumber'),
-            'tig_housenumber_addition', $request->getPostValue('tig-housenumber-addition')
+            'tig_housenumber_addition' => $request->getPostValue('tig-housenumber-addition')
         ];

         $this->attributeParser->set($attributes);
```

**Comment by rikwillems** [comment]
Maybe too quick, I see you can missing the street name value, not the housenumber addition. But anyway, this issue is also present.

**Comment by tig-jeffreybranderhorst** [comment]
Hi @rikwillems,

Thank you thinking along and submitting the code! In our upcoming version of the extension, this code has changed, we have refactored the extension completely. The RC of the refactor is live, and we will release the non-rc version soon as possible. 
Thank you again for thinking along! 

Have a great day,
Jeffrey
