### ISSUE TITLE
[BUG] When editing address data gets in the wrong fields

### ISSUE THREAD

**Issue by Aquive** [tig-nl/postcode-magento2#38]
**To Reproduce**
1. Make sure you have an account with an address with a housenummer addition (3rd street field).
2. Make sure to edit the address from your customer account (frontend)

**Expected result**
All the right data in the right fields.

**Actual result**
The streetname fields gets populated by the housenumber

**Workaround**
Just change/edit the data.

**Screenshots**
See attachment

** Please complete the following information**
- Magento version: 2.4.3-p1
- PHP version: 7.4.8
- TIG Postcode extension version: 1.4.1

<img width="1073" alt="Schermafbeelding 2022-01-27 om 16 01 25" src="https://user-images.githubusercontent.com/197229/151816852-4d6c7bc0-898b-4273-b200-5b649e803328.png">

**Comment by Aquive** [comment]
This seems the be related to another extension we use `experius/module-addresslines`. When it is disabled this is not an issue any more.

**Comment by tig-jeffreybranderhorst** [comment]
Hi @Aquive ,

We have released a new extension where the code is refactored. I suggest you try this again if the conflict with experius is still there and you wish it needs to be fixed you can contact us at support@tig.nl

Have a great day,
Jeffrey
