### ISSUE TITLE
[BUG] Housenumber addition field does not get updated/saved

### ISSUE THREAD

**Issue by Aquive** [tig-nl/postcode-magento2#39]
**To Reproduce**
1. Make sure to have an account with an address with an housenumber addition field filled in.
2. Try to change change to an address from a client account (frontend) where the housenumber addition field in not used.

**Expected result**
A complete address where the housenumber addition field is not filled in.

**Actual result**
The housenumber field still shows the data before the edit (e.g. de data for this field is not changed on save)

**Workaround**
None (That I know of)

** Please complete the following information**
- Magento version: 2.4.3-p1
- PHP version: 7.4.8
- TIG Postcode extension version: 1.4.1

**Comment by tig-jeffreybranderhorst** [comment]
Hi,

In the newest version of our extension, this should be fixed. If you still are having problem, you can always contact us at [support@tig.nl](mailto:support@tig.nl)

Have a great day,
Jeffrey

**Comment by Aquive** [comment]
I am out of office until the 7th of August. The fastest way to get answer for support issues is by emailing to ***@***.***

For other issues you may contact one of my colleagues Jeroen ***@***.***) or Ivo ***@***.***).
