### ISSUE TITLE
Wrong namespace plugin/mageplaza/AddressHelper gives blank page

### ISSUE THREAD

**Issue by GuidoHub** [tig-nl/postcode-magento2#4]
I am testing the module together with Mageplaza checkout but after installing your extension I am getting a blank page when opening onestepcheckout. After changing below file I can open it again only the fields are not positioned on sortOrder 3 but are placed at the bottom.

File: postcode-magento2/Plugin/Mageplaza/AddressHelper.php

row 32: namespace TIG\Postcode\Plugin\MagePlaza;

change: namespace TIG\Postcode\Plugin\Mageplaza;

**Comment by tig-rikjonkmans** [comment]
Hi @GuidoHub,

Thanks, you are absolute right about the namespace, sorry about that. But the sort order is strange, could you tell me which version of the MagePlaza checkout you are using ?

**Comment by GuidoHub** [comment]
I am using version 2.5.0, that's the latest version. When I run in developer mode it seems to position the fields the right way. Looks like the plugin is not triggered because that's the only thing it does, positioning the fields.

**Comment by tig-rikjonkmans** [comment]
Hi @GuidoHub,

Thanks for the info, i shall dive into it. When i have more information, i let you know.

**Comment by GuidoHub** [comment]
@tig-rikjonkmans ,

Oke thank you. I hope you can find it. One remark, you are using $fieldPostion instead of $fieldPosition but this is not the issue because you use it consistent;) and the function name is spelled correct.

**Comment by tig-rikjonkmans** [comment]
@GuidoHub,

Thanks for noticing, how embarrassed i am. Think i have to thank the auto-completion of the IDE ;) 

But anyway, i have found the problem, Mageplaza did some minor changes to their Layout processor which was causing the wrong sortOrder selection. We uses version 2.4.4 of the OSC in the time making this extension compatible. 

I have created a new version of the extension v1.1.6. which contains a fix for this issue.

**Comment by tig-rikjonkmans** [comment]
@GuidoHub,

Can you let me know if the new release solved the issue you have / had in your environment ?

**Comment by GuidoHub** [comment]
@tig-rikjonkmans 

Sorry for my late reply. I just downloaded the latest version on my test and it seems to work like it should be:) Will test some more tomorrow.

Thank you!
