### ISSUE TITLE
[BUG] Unnecessary extra step/action?

### ISSUE THREAD

**Issue by Aquive** [tig-nl/postcode-magento2#40]
Maybe not a bug per se. But I didn't know how to report it in another way.

**To Reproduce**
1. Go to checkout
2. Remove the checkbox for "Billing and shipping address are the same"

**Expected result**
I expect the dropdown menu with different addresses to show, so I can select another address. Just like Magento native behavior.

**Actual result**
Instead, the extension adds a new button called "Edit". After clicking this button, the dropdown does show up. But this step is unnecessary and a bit confusing.

**Workaround**
Actually use the button :)

**Screenshots**
See below

** Please complete the following information**
- Magento version: 2.4.3-p1
- PHP version: 7.4.8
- TIG Postcode extension version: 1.4.1

<img width="737" alt="Schermafbeelding 2022-01-27 om 16 15 36" src="https://user-images.githubusercontent.com/197229/151946400-cec5eb4c-cfb3-495b-837a-fbc835567a77.png">

**Comment by tig-jeffreybranderhorst** [comment]
Hi @Aquive,

Thank you for submitting this, we are going to investigate it further! 

Have a great day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment]
Hi @Aquive,

I can reproduce this, so I will place this on our backlog. I found another workaround, if you press the checkbox again the edit button disappears and changes into a Dropbox with your addresses. Does this workaround also works for you? 

I will place this on our backlog, thank you for submitting this issue. 

Have a great day,
Jeffrey

**Comment by Aquive** [comment]
Hi @tig-jeffreybranderhorst,

We are not using the extension yet. So a workaround is not needed for now. It would be great to see it fixed though.

Thanks for the support (again)!

**Comment by tig-jeffreybranderhorst** [comment]
Hi @Aquive,

I cannot give you an update yet, when it is fixed I will update you! 

Have a nice day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment]
Hello @Aquive ,

This should be fixed in our RC, could you please test the RC on a staging environment and let us know if it is not fixed for you. 

Have a great day,
Jeffrey

**Comment by tig-jeffreybranderhorst** [comment]
Hi @Aquive ,

We have released the RC, the newest version of the extension should now solve this. If it does not, you can always contact us at support@tig.nl

Have a great day,
Jeffrey
