### ISSUE TITLE
[BUG] Cannot proceed to next step in checkout

### ISSUE THREAD

**Issue by Aquive** [tig-nl/postcode-magento2#44]
**To Reproduce**
1. Configure the postcode module in test mode.
2. Try to checkout an item
3. Click on 'proceed' on first step of checkout after filling all the required fields

**Expected result**
Go to the next step of the checkout.

**Actual result**
Nothing happens. No console erros, no application logs entries. The street field is filled in as expected (a.k.a. the module is working)

**Workaround**
None found (yet)

** Please complete the following information**
- Magento version: 2.4.3-p2
- PHP version: PHP 7.4
- Postcode module version: 1.5.1

**Comment by tig-jeffreybranderhorst** [comment]
Hi @Aquive ,

I have installed the extension on a clean Magento 2.4.3-p2, and I cannot reproduce this. We can place orders without problems.  Do you have more extensions installed that it could be a conflict? 

Have a great day,
Jeffrey

**Comment by Aquive** [comment]
@tig-jeffreybranderhorst thanks for your reply.

It thought it was happening with a wrong test API key. But I cannot reproduce my own bug report anymore. 

I have (another) question though. What should happen when I set the modus to "off"? Since it seems not to affect checkout form. (a.k.a. off and test seem to behave in the same way).

**Comment by tig-jeffreybranderhorst** [comment]
Hi @Aquive ,

You are correct, It should stop hiding the field and not try to check the postal code and house number anymore. I see this still happens, I will create a bug issue for this. 

Have a great day,
Jeffrey

**Comment by Aquive** [comment]
@tig-jeffreybranderhorst thanks for that.

I can reproduce the reported issue again (unfortunately). Question: is there some sort of a limit set for test credentials? I am getting more/different weird results when trying to replicate/reproduce the issue consistently.

**Comment by Aquive** [comment]
@tig-jeffreybranderhorst 

I have been testing some more. This issue seems indeed to be caused by another extension:  `experius/module-addresslines`.

So I don't think the bug report isn't relevant anymore. If you would be kind enough to answer my above question about limits on the (test) API, I can close the issue.

**Comment by tig-jeffreybranderhorst** [comment]
Hi @Aquive ,

Good to read you figured out the issue. And to answer your question, the test credentials indeed have a limit each day. 

Have a great day,
Jeffrey

**Comment by Aquive** [comment]
@tig-jeffreybranderhorst 

Thanks. What is the day limit? Does the system give a warning/error when the limit is reached? It would be a good feature if not.

**Comment by tig-jeffreybranderhorst** [comment]
Hi @Aquive ,

The limit is  +/- 50 request.  Could be a bit more because of a load balancer, but the limit is 50. 

Have a great day,
Jeffrey
