### ISSUE TITLE
[BUG] Conflicting KO templates with TIG PostNL module

### ISSUE THREAD

**Issue by basvanpoppel** [tig-nl/postcode-magento2#45]
**To Reproduce**
1. Install both modules on latest version
2. Enable Postcode Checkout for NL, disable Postcode check in PostNL module
3. Go to checkout and fill shipping address
4. Go to second step

**Expected result**
The billing address should display the data filled in from shipping address (assuming billing address = same)

**Actual result**
House number is displayed twice. (Postcode module combines street & number in street field, PostNL module adds template which adds a number field after it)

**Workaround**
I've overridden three templates from PostNL module to prevent this issue:
TIG_PostNL/web/template/billing-address/details.html
TIG_PostNL/web/template/shipping-address/address-renderer/default.html
TIG_PostNL/web/template/shipping-information/address-renderer/default.html

**Screenshots**

** Please complete the following information**
- Magento version: 2.4.3-p2
- PHP version: PHP 7.4

**Comment by tig-jeffreybranderhorst** [comment]
Hi @basvanpoppel ,

Thank you for bringing this to our attention, we had also noticed this and made a fix that is not live yet.  In an upcoming PostNL version, this will be fixed. 

Have a great day,
Jeffrey

**Comment by JKetelaar** [comment]
Has this been fixed yet @tig-jeffreybranderhorst?

**Comment by tig-jeffreybranderhorst** [comment]
Hi @JKetelaar ,

We got a fix ready, but it is not released yet. It is going to be released when we make a PostNL release for the postcode checker. At this moment, I cannot give a date yet. 

Have a great day,
Jeffrey

**Comment by JKetelaar** [comment]
It's blocking our road to Magento 2.4.5... Could you provide an RC or early patch?

**Comment by tig-jeffreybranderhorst** [comment]
Hi @JKetelaar ,

This is the patch for PostNL that we made. You should first test it on a staging to be sure.
`--- a/view/frontend/web/template/billing-address/details.html
+++ b/view/frontend/web/template/billing-address/details.html
@@ -8,7 +8,7 @@
     <text args="currentBillingAddress().prefix"></text>  <text args="currentBillingAddress().firstname"></text> <text args="currentBillingAddress().middlename"></text>
     <text args="currentBillingAddress().lastname"></text> <text args="currentBillingAddress().suffix"></text><br/>
     <text args="currentBillingAddress().street.join(', ')" if="currentBillingAddress().street"></text>
-    <text args="tigHouseNumber()"></text><br/>
+    <br/>
     <text args="currentBillingAddress().city "></text>, <span text="currentBillingAddress().region"></span> <text args="currentBillingAddress().postcode"></text><br/>
     <text args="getCountryName(currentBillingAddress().countryId)"></text><br/>
     <a if="currentBillingAddress().telephone" attr="'href': 'tel:' + currentBillingAddress().telephone" text="currentBillingAddress().telephone"></a><br/>
--- a/view/frontend/web/template/shipping-address/address-renderer/default.html
+++ b/view/frontend/web/template/shipping-address/address-renderer/default.html
@@ -8,11 +8,7 @@
     <text args="address().prefix"></text> <text args="address().firstname"></text> <text args="address().middlename"></text>
     <text args="address().lastname"></text> <text args="address().suffix"></text><br/>
     <text args="address().street.join(', ')" if="address().street"></text>
-    <each args="data: address().customAttributes, as: 'element'">
-        <div class="tig-housenumber" if="element['attribute_code'] == 'tig_housenumber' || element['attribute_code'] == 'tig_housenumber_addition'">
-            <text args="element.value"></text>
-        </div>
-    </each><br/>
+    <br/>
     <text args="address().city "></text>, <span text="address().region"></span> <text args="address().postcode"></text><br/>
     <text args="getCountryName(address().countryId)"></text><br/>
     <a if="address().telephone" attr="'href': 'tel:' + address().telephone" text="address().telephone"></a><br/>
--- a/view/frontend/web/template/shipping-information/address-renderer/default.html
+++ b/view/frontend/web/template/shipping-information/address-renderer/default.html
@@ -8,11 +8,7 @@
     <text args="address().prefix"></text> <text args="address().firstname"></text> <text args="address().middlename"></text>
     <text args="address().lastname"></text> <text args="address().suffix"></text><br/>
     <text args="address().street.join(', ')" if="address().street"></text>
-    <each args="data: address().customAttributes, as: 'element'">
-        <if args="element['attribute_code'] == 'tig_housenumber' || element['attribute_code'] == 'tig_housenumber_addition'">
-            <text args="element.value"></text>
-        </if>
-    </each><br/>
+    <br/>
     <text args="address().city "></text>, <span text="address().region"></span> <text args="address().postcode"></text><br/>
     <text args="getCountryName(address().countryId)"></text><br/>
     <a if="address().telephone" attr="'href': 'tel:' + address().telephone" text="address().telephone"></a><br/>`

Have a great day,
Jeffrey

**Comment by JKetelaar** [comment]
Thanks a lot Jeffrey!
