### ISSUE TITLE
[BUG] Housenumber in shipping address is missing again

### ISSUE THREAD

**Issue by albundy2** [tig-nl/postcode-magento2#59]
**To Reproduce**

Go to checkout and fill in zipcode and housenumber
Address is shown and house number is shown
Finish the checkout and in the order e-email and backend admin the housenumber at the shipping address is missing again

**Expected result**
Housenumber is shown in mail and backend at orders

**Actual result**
Because the shipping house number is missing all Riverty payment options are rejected. And if we forget to fill it in before creating shipping labels the tracking code for PostNL isn't working. 

**Workaround**
Turning off address / Postcode check in the PostNL plugin solves the problem. 

** Please complete the following information**
- Magento version: 2.4.6p3
- PHP version: 8.1
- PostNL 1.16

Extra information:
This problem was there before in an older version, but was solved and now in version 1.16 I have the same problem again.
The Housenumber is only missing in the shipping address, Billing address is complete

**Comment by support-ps** [comment]
@albundy2 This seems to be PostNL related, not the Postcode Service. Can you confirm this?

**Comment by albundy2** [comment]
Correct, i placed the issue at the wrong plugin

Regards
Marcel

Van: support-ps ***@***.***>
Verzonden: woensdag 2 oktober 2024 18:35
Aan: postcodeservice/postcode-magento2 ***@***.***>
CC: albundy2 ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [postcodeservice/postcode-magento2] [BUG] Housenumber in shipping address is missing again (Issue #59)


@albundy2<https://github.com/albundy2> This seems to be PostNL related, not the Postcode Service. Can you confirm this?

-

**Comment by support-ps** [comment]
Clear, thanks. Can you close this issue?
