### ISSUE TITLE
Compatibility with magento/module-quote 101.0.6

### ISSUE THREAD

**Issue by MaartenWolfsen** [tig-nl/postcode-magento2#8]
The current module required magento/module-quote 101.0.5, but is locked at that version.
Since Magento 2.2.7 uses magento/module-quote 101.0.6, can you update the composer.json, so it also supports 101.0.6?

**Comment by tig-rikjonkmans** [comment]
Hi @MaartenWolfsen ,

Sorry for the late response, because we are about to release a stable of the 1.2 version which contains BE validation as well we released a RC first, which is compatible with M2.2.7

However i just released 1.1.12 which is also compatible with 2.1.16 and 2.2.7.

**Comment by maartenatmarissen** [comment]
@tig-rikjonkmans That's good to hear! Thank you for the response and releasing a new version, compatible with 2.2.7.

**Comment by MaartenWolfsen** [comment]
@tig-rikjonkmans  That's good to hear! Thank you for the response and releasing a new version, compatible with 2.2.7.
